### ISSUE TITLE
Is Vite supported?

### ISSUE THREAD

**Issue by davorpeic** [MauricioRobayo/react-obfuscate-email#177]
Hi, 
I use Vite and I get this error when running dev server

```
error when starting dev server:
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29511:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "react-obfuscate-email". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "react-obfuscate-email". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by MauricioRobayo** [comment]
Hi!

I'm sorry, Vite is not currently supported. :(

PRs are welcome!

**Comment by lmexo** [comment]
To me it appears you planned to make an ESM build... at least you added a path in package.json `{ "module": ... }`.

By removing the "module" from package.json, I got this lib working with vite without further changes.
