### ISSUE TITLE
Generates a page during production build

### ISSUE THREAD

**Issue by jordanlambrecht** [MauricioRobayo/react-obfuscate-email#374]
Hiya,

Right now, Screaming Frog and Google Search Console are picking up on ghost pages generated by ROE. Any ideas why or how to fix it?

<img width="1101" alt="Screen Shot 2022-10-06 at 11 23 25" src="https://user-images.githubusercontent.com/54866853/194367094-d8303d00-774b-4e1c-987f-745c1ca1d07d.png">

**Comment by MauricioRobayo** [comment]
Hello!

I don't see any reason why ROE will create those pages, are you sure those are generated by ROE? Could you share an example of the code you are using that could be generating those pages?

**Comment by jordanlambrecht** [comment]
Sure thing! Here's a few different examples:

```
            <div>
              <Lead color='blue-dark'>
                If you can work with these requirements, we would love to have you.
              </Lead>
              <p className='text-white text-2xl '>
                Shoot us an email{' '}
                <Obfuscate email={'careers@pixelbakery.com'} className={'underline text-white'} />{' '}
                with any questions. Fill out the form and we can get something scheduled. In the
                meantime, go ahead and follow us on social media (
                <a
                  href='https://instagram.com/pixelbakery'
                  target={'_blank'}
                  className='underline text-white'
                  rel='noreferrer'
                >
                  @pixelbakerylnk
                </a>
                ) to see more about life at PB.
              </p>
            </div>
```


```
import Obfuscate from 'react-obfuscate'
export const Footer: NextPage = () => {
return(
<li className='mt-3 text-xl text-cream'>
  <Obfuscate tel={'402-302-0323'} className={'text-cream  '}>
    402 302 0323
  </Obfuscate>
</li>
)
}
```

It's pretty straightforward code. Here's the repo if you want to poke around more: https://github.com/pixelbakery/pixelbakery-website

**Comment by jordanlambrecht** [comment]
omg I'm the dumbest person ever. I'm using react-obfuscate, not react-obfuscate-email. I'm so sorry =/
