### ISSUE TITLE
Typescript types files are not detected by typescript using npm 18+reactjs + vite

### ISSUE THREAD

**Issue by fgerards** [MauricioRobayo/react-obfuscate-email#821]

**Comment by ndmax** [comment]
@MauricioRobayo 

I receive the following error on `import { Email } from 'react-obfuscate-email';`

`Could not find a declaration file for module 'react-obfuscate-email'. '/path/to/project/node_modules/react-obfuscate-email/dist/react-obfuscate-email.mjs' implicitly has an 'any' type.
  There are types at '/path/to/project/node_modules/react-obfuscate-email/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-obfuscate-email' library may need to update its package.json or typings.`

Using:
````
    "react": "^18.2.0",
    "typescript": "^5.2.2",
    "vite": "^5.2.0"
````

**Comment by amcc** [comment]
same for me in Next v 14, node 20
